### PR TITLE
added s3_rgw support

### PR DESCRIPTION
**Pull request by dyvol777**
**What this PR does**:
added `s3_rgw` support

this change won't break anything

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by jsanda** [comment]
Thanks for the PR @dyvol777. Can you please sign the CLA if you haven't already done so? And can you also update the changelog?

**Comment by dyvol777** [comment]
I'm sorry, but i didn't find any info in repo on how to sign the CLA. Can you give me a bit information about it?
And for changelog,  i should add it for 1.6.0 or 1.5.1?

**Comment by adejanovski** [comment]
> I'm sorry, but i didn't find any info in repo on how to sign the CLA. Can you give me a bit information about it?
> And for changelog, i should add it for 1.6.0 or 1.5.1?

Hi,
The CLA is linked in the PR description: https://cla.datastax.com/

The changelog should be the 1.6.0 since this isn't a bug fix and will ship in our next minor release.

Thanks!

**Comment by dyvol777** [comment]
signed the CLA and added changelog

**Comment by adejanovski** [comment]
@dyvol777, quick question: wouldn't `s3_compatible` work for using CEPH RGW as backend?

**Comment by adejanovski** [comment]
Let's roll with s3_rgw then. Thanks for pushing this PR!

**Pull request merged**
