### PR TITLE
Update k8s versions for testing

### PR DESCRIPTION
**Pull request by Miles-Garnsey**
**What this PR does**:

* Bump all k8s versions for testing to latest patch release.
* Add k8s v1.22.3 to versions in k8s version test.

**Which issue(s) this PR fixes**:
#1165 

**Checklist**
- [ NA ] Changes manually tested
- [ NA ] Automated Tests added/updated
- [ NA ] Documentation added/updated
- [ NA ] CHANGELOG.md updated (not required for documentation PRs)
- [ NA ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by jeffbanks — COMMENTED** [review]
Looking at the k8s patch releases there are some more updated versions that were added in November if interested in getting the the latest and greatest.

**Review by jeffbanks — COMMENTED** [review]
Here's the supported image set we found for Kind 0.11.1:
`1.17.17`, `1.18.19`, `1.19.11`, `1.20.2`, `1.21.2`, `1.22.2`

Based on Docker image [reference ](https://hub.docker.com/r/kindest/node/tags?page=1&ordering=last_updated)for Kind.

**Comment by jdonenine** [comment]
How about we update this PR to just use whatever the latest Kind has, might as well.  Some won't even change I guess.  

From your list @jeffbanks looks like there is a newer 1.20 available:  https://hub.docker.com/layers/kindest/node/v1.20.7/images/sha256-4c68efafa97d278a75a5b4677fb27e4986b03301739f1f87575af32202da9cfe?context=explore

**Comment by jdonenine** [comment]
Actually, forget that 1.20.7 is what we already have.  Ah well, let's update as much as we can, not really more we can do.

**Comment by jeffbanks** [comment]
@Miles-Garnsey leaving this here as you had it as we were thinking we could take some of the upgrades for today's release, but not the case based on the Kind supported versions.  Sorry for the mess here ...

**Comment by Miles-Garnsey** [comment]
Apologies for this folks, it looks to me as though this PR is not very useful as:
* k8s 1.22 is added to the tests in another PR.
* My proposed versions will not work as kind is way behind k8s upstream on patch versions for some reason.

Annoying how we can't test these workflows without them being on `main`. I will close this.

**Pull request closed without merging**
