### PR TITLE
Add Stargate metrics to overview dashboard

### LINKED ISSUE #412: Stargate metrics don't show up in the dashboards
## Bug Report

**Describe the bug**
Stargate nodes expose metrics for Prometheus but they're not showing up in the dashboards. It appears that the scraping of Stargate nodes isn't implemented in `charts/k8ssandra/templates/prometheus/service_monitor.yaml`.

**To Reproduce**

* spin up a k8ssandra cluster with at least one Stargate node
* Enable port forwarding on the stargate service for port 9042
* Run a stress test with nosqlbench
* Check the Grafana Overview dashboard: request throughput should be very low compared to the actual throughput from the stress tool.

**Expected behavior**

* Request throughput in the Grafana dashboard should match the one from the stress tool.

**Screenshots**
This was captured during a 1000 ops/s 70%w/30%r stress test:

**Environment (please complete the following information):**
Mac OS

* Helm charts version info

```
% helm ls -A
NAME   	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART           	APP VERSION
demo   	k8ssandra	3       	2021-02-23 09:42:49.188099 +0100 CET	deployed	k8ssandra-0.38.0	3.11.7
traefik	traefik  	1       	2021-02-23 09:18:04.672966 +0100 CET	deployed	traefik-9.14.2  	2.4.2
```

* Kubernetes cluster kind:

Kind 1.17

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-119) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-1.3.0

### PR DESCRIPTION
**Pull request by emerkle826**
**What this PR does**:
Add Stargate metrics charts to the Cassandra Overview Grafana dashboard.

**Which issue(s) this PR fixes**:
Fixes #412 

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by emerkle826** [comment]
I'm not sure of an easy way to make part of the Grafana Cassandra [Overview dashboard](https://github.com/emerkle826/k8ssandra/blob/stargate-metrics/charts/k8ssandra/dashboards/overview.json) dependent upon if Stargate is enabled, so I duplicated it into [overview-with-stargate.json](https://github.com/emerkle826/k8ssandra/blob/stargate-metrics/charts/k8ssandra/dashboards/overview-with-stargate.json), added the Stargate charts to it, and added the conditional to [yaml](https://github.com/emerkle826/k8ssandra/blob/stargate-metrics/charts/k8ssandra/templates/cassandra/overview-dashboard.yaml) to pick which dashboard template to use based on Stargate enablement. If there is a better way, I'd appreciate some tips.

**Comment by emerkle826** [comment]
@adejanovski I combined the charts as you suggested. Below is a screen shot of a Stargate run followed by a direct to Cassandra run.

Screenshot_2021-06-10_15-47-53

**Comment by adejanovski** [comment]
Brilliant! Let me give this a try.

**Comment by emerkle826** [comment]
> Would it be possible to change the color of either one of these two to make it stand out?

Sure thing.

**Comment by emerkle826** [comment]
commit https://github.com/k8ssandra/k8ssandra/pull/867/commits/825e09445e6f5af3416cca4e5c30286c0001590c sets the colors on the Request Throughput chart to the following:
Screenshot_2021-06-11_08-28-32

**Review by adejanovski — APPROVED** [review]
Great stuff @emerkle826, approved ✅ 

:shipit: :shipit: :shipit:

**Pull request merged**
