### PR TITLE
cass-operator v1.7.1, add TestUpgradeScenario to GHA

### PR DESCRIPTION
**Pull request by burmanm**
**What this PR does**:
Add TestUpgradeScenario to GHA integration test step, upgrades cass-operator to v1.7.1

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by burmanm** [comment]
And as soon as I asked, the next run had all the necessary logs. Ouh well.

Well, it fails as expected to the "  Warning  ReconcileFailed     12m (x10 over 12m)  cass-operator  StatefulSet.apps "k8ssandra-dc1-default-sts" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"

Oddly, it did not fail on my machine to that..

**Comment by adejanovski** [comment]
> Oddly, it did not fail on my machine to that..

That suggests that the upgrade maybe didn't really happen I'd say.  Worth checking why it's passing locally.

**Comment by burmanm** [comment]
I found the reason why it passed, the charts versions pulled some old stuff that deployed 1.6.0

**Comment by burmanm** [comment]
The 4.0 upgrade test failures seem unrelated to this PR. "Warning  FailedMount  15m   kubelet, kind-worker3  MountVolume.SetUp failed for volume "k8ssandra-cass-operator-token-mmqdp" : failed to sync secret cache: timed out waiting for the condition" as well as Reaper being unable to start. So some sort of timeouts.

**Review by adejanovski — APPROVED** [review]

**Pull request merged**
