### PR TITLE
Upgrade Reaper dependency 2.2.2 -> 2.2.5

### PR DESCRIPTION
**Pull request by adejanovski**
This is auto-generated update from the K8ssandra upgrade GHA workflow.
Check that CI passes correctly before merging this PR.

### CODE REVIEW

**Review by jsanda — COMMENTED** [review]
How come it introduced all the formatting changes?

Do you think we should also change the default version in reaper-operator?

**Comment by adejanovski** [comment]
> How come it introduced all the formatting changes?

The values files update is done using yq, which seems to reformat the file according to its own standard. I guess once we merge one of these PRs, we'll be good.
 
> Do you think we should also change the default version in reaper-operator?

I'll answer with more questions: do you think we should include the operators in the list of upgraded dependencies so that we get upgrade PRs for them as well? Should we upgrade both Reaper and reaper-operator at the same time then or separately? Same question for medusa/medusa-operator.

**Comment by jsanda** [comment]
Thinking out loud... 

I would like to say we do Reaper --> reaper-operator --> k8ssandra and same for Medusa. The reality is that we have end to end test coverage in k8ssandra whereas it is lacking in reaper-operator and in medusa-operator. And even if we had more thorough test coverage in the operator repos, the tests in k8ssandra are authoritative. 

I am in favor of Reaper -->k8ssandra --> reaper-operator.

**Comment by adejanovski** [comment]
> I am in favor of Reaper -->k8ssandra --> reaper-operator.

Sounds good

**Pull request merged**
