### PR TITLE
[K8SSAND-2] Update NPM packages

### LINKED ISSUE #761: Resolve Dependabot alerts on K8ssandra repo related to documentation.
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-2) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by jdonenine**
**What this PR does**:
* Using `npm audit fix` to resolve audit issues with existing packages
* Locally confirmed `hugo` and `hugo server` both work after the upgrades.

**Which issue(s) this PR fixes**:
Fixes #761

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [x] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by bradfordcp** [comment]
Looking through the repo I'm trying to understand why we have a `package-lock.json` file in the repo root. If it's not needed can we remove that as part of this PR?

**Comment by jdonenine** [comment]
> Looking through the repo I'm trying to understand why we have a `package-lock.json` file in the repo root. If it's not needed can we remove that as part of this PR?

Sorry @bradfordcp just now saw your comment about the stray file, I removed that as well, so it's included here in this PR now.

**Comment by jdonenine** [comment]
@bradfordcp can you give this another look when you have a chance? I think we're good to go.

**Review by bradfordcp — APPROVED** [review]
LGTM :+1:

**Pull request merged**
