### PR TITLE
Make TESTS and GO_FLAGS conditional so they can be set from cmd line

### LINKED ISSUE #507: TESTS and GO_FLAGS Makefile vars cannot be set from command line
## Bug Report

**Describe the bug**
The `TESTS` and `GO_FLAGS` variables were introduced to give more control over unit test execution, but they currently cannot be set from the command line.

**To Reproduce**
1. Run `GO_FLAGS="-v" TESTS=".*auth.*" make unit-test`
2. All unit tests are run with non-verbose output

**Expected behavior**
I should be able to set these vars from the command line.

**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info

1.0.0

* Helm charts user-supplied values

`$ helm get values RELEASE_NAME` 

* Kubernetes version information:

`kubectl version`

* Kubernetes cluster kind:

**Additional context**

### PR DESCRIPTION
**Pull request by jsanda**
**What this PR does**:
Makes the `TESTS` and `GO_FLAGS` Makefile vars conditional so that they can be set from the cmd line.

**Which issue(s) this PR fixes**:
Fixes #507

**Checklist**
- [x] Changes manually tested
- [ ] Chart versions updated (if necessary)
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [ ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by burmanm** [comment]
So what's the behavioral change? They were always settable from the command line.

**Comment by burmanm** [comment]
Actually I can't find any difference when testing with ``make GO_FLAGS="-v" TESTS="wontmatch" test`, it functions the same with both versions.

**Comment by jsanda** [comment]
> So what's the behavioral change? They were always settable from the command line.

No they were not settable from the command line. I tested and verified this by adding this target:

```make
MSG=foo
echo-test:
	echo $(MSG)
```

Running `MSG=bar make echo-test` still outputs `foo`.

But when I change it to

```make
MSG?=foo
echo-test:
	echo $(MSG)
```
and then run `MSG=bar make echo-test` the output is `bar` as expected.

**Comment by jsanda** [comment]
Ok, now I did the following:

```
$ make MSG=bar echo-test
echo bar
bar
```
@burmanm do you know why there is a difference in behavior when setting the var before the `make` command?

**Comment by burmanm** [comment]
If it's after make command then it's a parameter for make (it could be -t etc also and we could catch that). The one before make is a shell variable.

**Comment by jsanda** [comment]
Then I can go ahead and close this. Thanks for the explanation!

**Pull request closed without merging**
