### PR TITLE
Make Prometheus namespace scoped

### PR DESCRIPTION
**Pull request by burmanm**
Closes issue #114

Updates Prometheus stack and Prometheus itself (provides newer UI if user does not wish to use Grafana)

### CODE REVIEW

**Review by jsanda — CHANGES_REQUESTED** [review]
I get the following RBAC related errors when I deploy from your branch:

`level=error ts=2021-01-12T04:03:55.281696812Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps is forbidden: User \"system:serviceaccount:default:k8ssandra-kube-prometheus-operator\" cannot list resource \"configmaps\" in API group \"\" at the cluster scope"
level=error ts=2021-01-12T04:03:56.202298166Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.PrometheusRule: failed to list *v1.PrometheusRule: prometheusrules.monitoring.coreos.com is forbidden: User \"system:serviceaccount:default:k8ssandra-kube-prometheus-operator\" cannot list resource \"prometheusrules\" in API group \"monitoring.coreos.com\" at the cluster scope"`

`level=error ts=2021-01-12T04:03:56.31421891Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User \"system:serviceaccount:default:k8ssandra-kube-prometheus-operator\" cannot list resource \"secrets\" in API group \"\" at the cluster scope"
level=error ts=2021-01-12T04:04:00.812635787Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1alpha1.AlertmanagerConfig: failed to list *v1alpha1.AlertmanagerConfig: alertmanagerconfigs.monitoring.coreos.com is forbidden: User \"system:serviceaccount:default:k8ssandra-kube-prometheus-operator\" cannot list resource \"alertmanagerconfigs\" in API group \"monitoring.coreos.com\" at the cluster scope"`

`level=error ts=2021-01-12T04:04:18.717908063Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User \"system:serviceaccount:default:k8ssandra-kube-prometheus-operator\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope"
level=error ts=2021-01-12T04:04:19.347222738Z caller=klog.go:96 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.ServiceMonitor: failed to list *v1.ServiceMonitor: servicemonitors.monitoring.coreos.com is forbidden: User \"system:serviceaccount:default:k8ssandra-kube-prometheus-operator\" cannot list resource \"servicemonitors\" in API group \"monitoring.coreos.com\" at the cluster scope"`

**Comment by jsanda** [comment]
I was able to resolve the errors with a couple changes to `k8ssandra/values.yaml`:

```yaml
# Default values for k8ssandra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cass-operator:
  # Namespace-scoped installs are currently not (well) supported.
  # See K8C-19 for details.
  clusterWideInstall: true

  # We need to use a patched version of cass-operator for now that has changes needed in
  # for Reaper and Medusa integration. Images will be built from
  # https://github.com/jsanda/cass-operator/tree/k8ssandra.
  image: jsanda/cass-operator:91205f4d8f1e

kube-prometheus-stack:
  
  prometheusOperator:
    admissionWebhooks:
      enabled: false
    namespaces:
      releaseNamespace: true
      additional: []

  alertmanager:
    enabled: false

  kubeStateMetrics:
    enabled: false

  grafana:
    enabled: false

  nodeExporter:
    enabled: false

  kubeletService:
    enabled: false

  kubeControllerManager:
    enabled: false

  kubelet:
    enabled: false

  kubeApiServer:
    enabled: false

  prometheus:
    enabled: false
```
Even if this works, I think we will run into another issue. You cannot use variables for property values in `values.yaml`. This means we cannot have something like `namespaceScoped: true` which will result in,

```yaml
  prometheusOperator:
    admissionWebhooks:
      enabled: false
    namespaces:
      releaseNamespace: true
      additional: []
```
We would need to use something like https://github.com/roboll/helmfile in order to support that behavior. I am not however advocating that we go down that path.

**Comment by burmanm** [comment]
I thought we don't need to allow both non-namescape-scoped as well namespace-scoped Prometheus installation? I would say if the customer wants to use their own Prometheus installation then we would just disable installation of our stack (as seen in the Rancher comment)

**Comment by jsanda** [comment]
>I thought we don't need to allow both non-namescape-scoped as well namespace-scoped Prometheus installation?

Ideally we can support both. Here is a scenario I had in mind. C* clusters are getting provisioned and torn down on a regular, frequent basis. I want to use cluster-wide Grafana and Prometheus instances across those clusters.

**Comment by jsanda** [comment]
Now that #176 has been merged, I don't think we need this anymore.

**Pull request closed without merging**
