### PR TITLE
update charts for k8ssandra-operator 0.4.0

### LINKED ISSUE #1284: K8SSAND-1220 ⁃ Update k8ssandra-operator chart to v0.4.0
k8ssandra-operator 0.4.0 was just [released](https://github.com/k8ssandra/k8ssandra-operator/releases/tag/v0.4.0). The chart needs to updated to make that the default version.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1220) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1220
┆priority: Medium

### PR DESCRIPTION
**Pull request by jsanda**
**What this PR does**:
Updates the k8ssandra-operator and cass-operator charts. The cass-operator chart had to be updated as well because k8ssandra-operator uses functionality in cass-operator that has not yet been released. This includes CRD changes as well.

**Which issue(s) this PR fixes**:
Fixes #1284

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by jsanda** [comment]
Unit tests are failing because of the cass-operator chart version change in the PR. GHA executes `scripts/update-helm-deps.sh` which loads chart dependencies from the file system. I intentionally did not update the cass-operator dependency for the k8ssandra chart. I don't think we want to. I may need to update the GHA job to add the k8ssandra chart repo so it can pull the older cass-operator chart version needed by the k8ssandra chart.

**Review by jeffbanks — APPROVED** [review]
LGTM, just the unit test item you mentioned.

**Review by jdonenine — APPROVED** [review]
I haven't had a chance to test things but if you want to go ahead and merge things look as expected.

**Comment by jdonenine** [comment]
I got through a multi-cluster test and all worked as expected with the new chart and operator version 💥 

```
$ helm ls -n k8ssandra-operator
NAME              	NAMESPACE         	REVISION	UPDATED                                	STATUS  	CHART                    	APP VERSION
k8ssandra-operator	k8ssandra-operator	1       	2022-02-06 10:37:30.644741607 -0500 EST	deployed	k8ssandra-operator-0.35.0	0.4.0
```

```
$ kd deployment k8ssandra-operator -n k8ssandra-operator | grep "Image"
    Image:      docker.io/k8ssandra/k8ssandra-operator:v0.4.0
```

```
$ kubectl exec --stdin --tty demo-dc1-default-sts-0 -n k8ssandra-operator -- nodetool -u $CASS_USERNAME -pw $CASS_PASSWORD status
Defaulted container "cassandra" out of: cassandra, server-system-logger, jmx-credentials (init), server-config-init (init)
Datacenter: dc1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load        Tokens  Owns (effective)  Host ID                               Rack
UN  172.18.0.10  96.79 KiB   16      100.0%            2aaf1327-c358-4615-bc33-2e3a01ec1e8d  default
UN  172.18.0.9   96.8 KiB    16      100.0%            500c8f19-7569-433b-95f7-9183c83fbb25  default
UN  172.18.0.11  116.72 KiB  16      100.0%            fb792722-54f1-41f6-81d1-b9773e5e665f  default

Datacenter: dc2
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load        Tokens  Owns (effective)  Host ID                               Rack
UN  172.18.0.12  89.87 KiB   16      100.0%            0a1e9262-d132-430a-a7a0-26d6aa0f43e7  default
UN  172.18.0.16  89.85 KiB   16      100.0%            b71cbe6d-08b3-42d5-a5fc-22488248d1ed  default
UN  172.18.0.13  89.87 KiB   16      100.0%            fb84f46e-205e-4719-9d37-78aec1e2a4c0  default

Datacenter: dc3
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load        Tokens  Owns (effective)  Host ID                               Rack
UN  172.18.0.21  84.57 KiB   16      100.0%            11634abe-9032-40ed-97a9-77c6a1176e00  default
UN  172.18.0.20  84.57 KiB   16      100.0%            63ef0266-4c56-4a08-b9ba-57e3fc3453de  default
UN  172.18.0.18  84.57 KiB   16      100.0%            f00bd86f-7b3a-41b7-ba62-bced70333358  default
```

I talked to @jsanda quickly, I'm going to ahead and merge.

**Pull request merged**
