### PR TITLE
499 gomod updates fix

### LINKED ISSUE #499: Go Module - Helm Upgrade
A version of Helm v2 was referenced in go.mod for k8ssandra.  This was found to be introduced as part of integration test packages referenced for building out common utils.

**To Reproduce**
Current main branch's `go.mod` includes the following entries:

```golang
require (
	github.com/datastax/cass-operator v1.5.1-0.20210112050706-a45fd80b40e0
	github.com/gruntwork-io/terratest v0.30.15
	github.com/k8ssandra/reaper-operator v0.0.0-20210122200305-0d6525659e9d
	github.com/onsi/ginkgo v1.14.2
	github.com/onsi/gomega v1.10.3
	github.com/stretchr/testify v1.6.1 // indirect
	github.com/traefik/traefik/v2 v2.3.7
	k8s.io/api v0.18.6
	k8s.io/apimachinery v0.18.6
	k8s.io/client-go v12.0.0+incompatible
	k8s.io/helm v2.16.3+incompatible
	sigs.k8s.io/controller-runtime v0.6.4
)
```

**Expected behavior**

Removal of helm `v2.16.3` and necessary changes to support helm `v3.5.2`.

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-127) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-127
┆Priority: Medium

### PR DESCRIPTION
**Pull request by jeffbanks**
**Which issue(s) this PR fixes**:
Fixes #499 

**Checklist**
- [x] Changes manually tested
- [ ] Chart versions updated (if necessary)
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by jsanda — COMMENTED** [review]
These dependency changes not only impact tests but the cleaner pre-delete hook. We need to make sure that these changes do not break compatibility with earlier versions going back to 1.16.

@jeffbanks have you tested against earlier k8s versions to verify it won't cause any issues?

**Comment by jeffbanks** [comment]
@jsanda I did startup against `v1.16.15` just now to check for anything during initialization/setup.  I will add a comprehensive set of versions check as defined in our test plan.  

@burmanm, it would be good to a few test runs locally from you as well as there were quite a few adjustments in versions.

```
NAME                                                  READY   STATUS      RESTARTS   AGE
k8ssandra-cass-operator-547845459-2tzqj               1/1     Running     0          10m
k8ssandra-dc1-default-sts-0                           2/2     Running     0          10m
k8ssandra-dc1-stargate-776f88f945-pgw2c               1/1     Running     0          10m
k8ssandra-grafana-86d4dd94d5-p5xx4                    2/2     Running     0          10m
k8ssandra-kube-prometheus-operator-5bdd97c666-rxtzg   1/1     Running     0          10m
k8ssandra-reaper-58c6f96d7b-6n4sr                     1/1     Running     0          4m23s
k8ssandra-reaper-operator-858cd89bdd-x49ls            1/1     Running     0          10m
k8ssandra-reaper-schema-9q47h                         0/1     Completed   0          5m13s
prometheus-k8ssandra-kube-prometheus-prometheus-0     2/2     Running     1          10m
traefik-56df6f955c-srhfd                              1/1     Running     0          11m
```

```
NAME                              STATUS   ROLES    AGE   VERSION
k8ssandra-cluster-control-plane   Ready    master   13m   v1.16.15
k8ssandra-cluster-worker          Ready    <none>   13m   v1.16.15
k8ssandra-cluster-worker2         Ready    <none>   13m   v1.16.15
k8ssandra-cluster-worker3         Ready    <none>   13m   v1.16.15
```

**Question**: do we have any documented steps (or can you draft some up here) that I can use to verify the particular `clean pre-delete hooks`?  I don't see those in our current 1.0 test plan.

**Comment by jeffbanks** [comment]
@burmanm can you point me to some information to use utilize the `cleaner pre-delete hook`?  I'm able to startup k8ssandra (all enabled components), with various k8s versions (including 1.16.x) using the updated dependencies.  @jsanda has brought up that we need to verify against with the cleaner pre-delete hooks.

**Comment by burmanm** [comment]
You need to rebuild the image and use that as override for the cleaner-image (otherwise it picks the older working one). And then do helm uninstall && delete namespace (and verify that cassdc was deleted by the pre-delete hook correctly)

**Pull request closed without merging**
