### PR TITLE
Allow setting autoscheduling to enabled in the values

### LINKED ISSUE #95: Add support for auto scheduling in Reaper CRD
**Describe the solution you'd like**
Add support for auto scheduling in Reaper CRD

**Additional context**
Legacy reference: [Jira K8C-68](https://k8ssandra.atlassian.net/browse/K8C-68)

### PR DESCRIPTION
**Pull request by burmanm**
Fixes #95, requires update of reaper-operator.

### CODE REVIEW

**Review by jsanda — CHANGES_REQUESTED** [review]
Can you update the image  in `charts/k8ssandra-cluster/templates/reaper-operator/deployment.yaml` to

```yaml
image: docker.io/k8ssandra/reaper-operator:73199f440649
``` 

Can you also bump the version numbers in the each `Chart.yaml`? For now all of the charts need to be on the same version.

**Comment by burmanm** [comment]
I think the last commit should be enough for #53 also

**Review by jsanda — CHANGES_REQUESTED** [review]
Can you bump the versions to 0.13.0?

I snuck in a PR last night that already moved them to 0.12.0 :)

**Comment by jsanda** [comment]
> I think the last commit should be enough for #53 also

Yup, that will work!

**Review by jakerobb — APPROVED** [review]
LGTM.

**Review by jsanda — APPROVED** [review]

**Pull request merged**
