### PR TITLE
pod => container in Cassandra pod docs

### PR DESCRIPTION
**Pull request by mproch**
pod => container in Cassandra pod docs

### CODE REVIEW

**Comment by jsanda** [comment]
Hi @mproch  

Thank you for submitting the PR! Before we can accept any contributions, we need you to sign the CLA at https://cla.datastax.com/.

Thanks

John

**Review by jsanda — COMMENTED** [review]
Nice find! 

I can merge as soon as you confirm that you have signed the CLA.

**Comment by mproch** [comment]
Hi, I signed CLA electronically - don't know if you can verify it?

**Review by jsanda — APPROVED** [review]
Thanks!

**Pull request merged**
